'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '../..');
const gradle = fs.readFileSync(path.join(root, 'android/app/build.gradle'), 'utf8');
const dirtyBlock = gradle.match(/def dirtyFiles = \['git', 'status', '--porcelain', '--',[\s\S]*?\n\s*\}\n\s*gitDirty/);
assert.ok(dirtyBlock, 'APK identity must derive dirty state from a scoped git status query');
assert.doesNotMatch(dirtyBlock[0], /!line\.startsWith\(['"]\?\?['"]\)/,
  'untracked production sources can enter the APK snapshot and must not be ignored');
for (const input of [
  "'app.py'", "'engine'", "'server'", "'static'", "'templates'", "'sources'",
  "'requirements-android.txt'", "'android/app/src'",
  "'android/app/build.gradle'", "'android/build.gradle'", "'android/settings.gradle'",
  "'android/gradle.properties'", "'android/gradle'",
  "'android/mobile-seed-policy.json'", "'android/seed-history.json'",
]) {
  assert.ok(dirtyBlock[0].includes(input), `APK identity must track packaged input ${input}`);
}

const identityTask = gradle.match(/tasks\.register\('writeBuildIdentity'\)\s*\{[\s\S]*?\n\}/)?.[0];
assert.ok(identityTask, 'build identity must be generated by a dedicated Gradle task');
assert.match(gradle, /gitRevFull = \['git', 'rev-parse', 'HEAD'\]/,
  'the full source revision must be captured during Gradle configuration');
assert.match(gradle, /rootProject\.ext\.buildGitRevisionFull = gitRevFull/,
  'the build identity task must receive the full captured source revision');
for (const input of [
  "inputs.property('sourceRevision', revisionValue)",
  "inputs.property('sourceDirtyState', dirtyValue)",
  "inputs.property('versionName', versionNameValue.toString())",
  "inputs.property('versionCode', versionCodeValue.toString())",
]) {
  assert.ok(identityTask.includes(input),
    `Gradle incremental task inputs must include ${input}`);
}
assert.doesNotMatch(identityTask, /\.execute\(/,
  'the task action must write the revision captured at configuration time');
assert.match(gradle, /android\.sourceSets\.androidTest\.assets\.srcDir\(buildIdentityDir\)/,
  'the instrumentation APK must embed the same build identity as the release APK');
assert.match(gradle, /mergeDebugAndroidTestAssets/,
  'the instrumentation asset merge must depend on the identity generator');

console.log('build_identity.test.js: ALL ASSERTIONS PASSED');
